version: "3.8"
services:
  app:
    image: rabbitclient
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:9080"
    networks:
      - rabbit-network
    volumes:
      - ./logs:/var/www/logs
    env_file:
      - variables.env
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbit-network
    volumes:
      - ./data/:/var/lib/rabbitmq/
      - ./logs/rabbitmq/:/var/log/rabbitmq/
    env_file:
      - variables.env
    environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
networks:
  rabbit-network:
    driver: bridge